services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - REDIS_URL=redis://redis:6379/0
      - ROOT_PATH=${ROOT_PATH}
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./api:/app/api
      - ./main.py:/app/main.py
      - ./cli.py:/app/cli.py
    command: uvicorn main:api --host 0.0.0.0 --port 8000 --reload

volumes:
  redis_data: